// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messenger.proto
// Protobuf Java Version: 4.26.0

package grpc;

public final class MessengerProto {
  private MessengerProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      MessengerProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017messenger.proto\"D\n\016MessageRequest\022\016\n\006s" +
      "ender\030\001 \001(\t\022\021\n\trecipient\030\002 \001(\t\022\017\n\007messag" +
      "e\030\003 \001(\t\"!\n\017MessageResponse\022\016\n\006status\030\001 \001" +
      "(\t\"\037\n\013UserRequest\022\020\n\010username\030\001 \001(\t\"\037\n\013M" +
      "essageList\022\020\n\010messages\030\001 \003(\t2s\n\tMessenge" +
      "r\0222\n\013sendMessage\022\017.MessageRequest\032\020.Mess" +
      "ageResponse\"\000\0222\n\022getMessagesForUser\022\014.Us" +
      "erRequest\032\014.MessageList\"\000B\030\n\004grpcB\016Messe" +
      "ngerProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MessageRequest_descriptor,
        new java.lang.String[] { "Sender", "Recipient", "Message", });
    internal_static_MessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MessageResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_MessageList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MessageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MessageList_descriptor,
        new java.lang.String[] { "Messages", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
