// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messenger.proto

// Protobuf Java Version: 4.26.0
package grpc;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
