// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messenger.proto

// Protobuf Java Version: 4.26.0
package grpc;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
